name: Zip Specific Folder

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Permisos para leer y escribir contenido

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    # Cambia 'ruta/a/la/carpeta' por la ruta real de tu carpeta
    - name: Zip specific folder
      run: zip -r carpeta.zip REI - Combinatoria

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create or Update Release
      id: create_or_update_release
      run: |
        release_id=$(gh release view v1.0.0 --json id --jq '.id' || echo "")
        if [ -z "$release_id" ]; then
          gh release create v1.0.0-${{ env.date }} carpeta.zip --title "Release v1.0.0-${{ env.date }}"
        else
          gh release upload $release_id carpeta.zip --clobber
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print Release URL
      run: echo "Release URL: https://github.com/${{ github.repository }}/releases/download/v1.0.0-${{ env.date }}/carpeta.zip"
