name: Zip Specific Folder and Update Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Permisos para leer y escribir contenido

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Cambia 'ruta/a/la/carpeta' por la ruta real de tu carpeta
    - name: Zip specific folder
      run: zip -r carpeta.zip REI - Combinatoria

    - name: Update Release
      id: update_release
      run: |
        release_id=$(gh release view v1.0.0 --json id --jq '.id')
        gh release upload $release_id carpeta.zip --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
